# Build for both .net standard 2.0 and .net framework 2.0/4.5 + nuget publish

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.3' 

- task: DotNetCoreCLI@2
  displayName: Build .net standard 2.0
  inputs:
    command: 'build'
    projects: '**/netstandard.csproj'
    configuration: '$(BuildConfiguration)'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: MSBuild@1
  displayName: Build .net framework 2.0
  inputs:
    solution: '**/net20.csproj'
    platform: 'AnyCPU'
    configuration: '$(BuildConfiguration)'

- task: MSBuild@1
  displayName: Build .net framework 4.5
  inputs:
    solution: '**/net45.csproj'
    platform: 'AnyCPU'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test .net standard 2.0
  inputs:
    command: 'test'
    projects: '**/test.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    testRunTitle: '.net standard test'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: Prepare nuget package
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: '**/Zipstorer.nuspec'
    versioningScheme: 'off'

- task: ManualIntervention@8
  inputs:
    instructions: 'Publish to nuget.org?'
    emailRecipients: 'jaime_olivares@hotmail.com'

- task: NuGetCommand@2
  displayName: Publish nuget package
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'
    versioningScheme: 'off'