# Build for both .net standard 2.0 and .net framework 4.5 + nuget publish

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build .net standard 2.0
  inputs:
    command: 'build'
    projects: '**/netstandard.csproj'
    configuration: '$(BuildConfiguration)'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: MSBuild@1
  displayName: Build .net framework 4.5
  inputs:
    solution: '**/net45.csproj'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: '$(BuildConfiguration)'
    restoreNugetPackages: true

- task: DotNetCoreCLI@2
  displayName: Test .net standard 2.0
  inputs:
    command: 'test'
    projects: '**/test.csproj'
    configuration: '$(BuildConfiguration)'
    testRunTitle: '.net standard test'
    feedsToUse: 'select'
    versioningScheme: 'off'
